import {Poppins} from "next/font/google";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import Providers from "./Provider";


const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700", "900"],
  subsets: ['latin'], // ✅ This is required!
  preload: true, // optional, true by default
});

export const metadata = {
  title: "Samarthan Setu - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
